config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  root 'pages#home'
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end
  get 'user/:id', to: 'users#show', as: 'user'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  validates_presence_of :name
  scope :public_rooms, -> {where(is_private: false)}
  after_create_commit { broadcast_append_to 'rooms' }
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end

  private
  def msg_params
    params.require(:message).permit(:body, :room_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)


    render 'index'
  end

  def show 
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)

    render 'index'
  end
  def create
    @room = Room.create(name: params["room"]["name"])
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <div class="navbar bg-base-100 px-4">
    <div class="flex-1">
      <a class="btn btn-ghost normal-case text-xl"> <%= current_user.email%> </a>
    </div>
    <div class="flex-none gap-2">
      <div class="avatar placeholder">
        <div class="bg-neutral-focus text-neutral-content rounded-full w-12">
          <span class="text-xl"> <%= current_user.email.first.capitalize %> </span>
        </div>
      </div> 
    </div>
  </div>    
<% end %>

app/views/layouts/_new_message_form.html.erb
<div class="text-center">
  <%= form_with(model: [@single_room, @message], remote: true, class: 'flex justify-center gap-4 mr-8 mt-4') do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'textarea textarea-bordered w-1/2', placeholder: 'Digite uma mensagem', autocomplete: 'off' %>
    <div>
      <%= f.submit data: { disable_with: false }, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: 'flex gap-2 mb-4') do |f| %>
  <%= f.text_field :name, class: 'input input-bordered input-sm w-full max-w-xs', autocomplete: 'off'%>
  <%= f.submit data: {disable_with:false}, class: 'btn btn-sm' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@2.6.0/dist/full.css"
      rel="stylesheet"
      type="text/css"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <%= javascript_importmap_tags %>
    <style>
      ::-webkit-scrollbar {
        display: none;
      }
      <%= ".msg-#{current_user&.id}"%>{
        background-color: #007bff !important;
        padding: 10px;
        width: 100%;
      }
      <%= ".cont-#{current_user&.id}"%>{
        display: flex;
        justify-content: flex-end;
      }
    </style>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %> relative mt-10 ml-20 mb-10 break-words">
  <div class="msg-<%= message.user.id %> bg-gray-800 text-white rounded-lg p-4 max-w-sm shadow-lg">
    <% unless message.room.is_private %>
      <h6 class="name text-gray-400 text-sm italic mb-2"><%= message.user.email %></h6>
    <% end %>
    <p class="text-sm leading-snug"><%= message.body %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="flex items-center flex-col justify-center h-screen">
  <div>
    <h1 class="text-3xl font-bold">Welcome to the Carlos TurboChat</h1>
  </div>
  <div class="text-center">
    <% if current_user %>
      <p >Logged in as <%= current_user.email %> </p>
      <%= link_to "Start chatting", rooms_path %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete, data: {  turbo_method: :delete} %>
    <% else %>
      <p> <%= link_to "If you already have an account you can login", new_user_session_path, class:'link link-hover' %></p>
      <p>or</p>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %> 
  </div>
</div>

app/views/rooms/_room.html.erb
<%= link_to room do %>
<div class="tooltip" data-tip="<%= room.name %>">
  <div class="avatar placeholder flex items-center gap-2">
    <div class="bg-neutral-focus text-neutral-content rounded-full w-8">
      <span class="text-xs"><%= room.name.first.capitalize %></span>
    </div>
    <p class="text-center"><%= room.name %></p>
  </div>
</div>
<% end %>

app/views/rooms/index.html.erb
<div class="grid grid-cols-3">
  <div class="container p-4 flex flex-col gap-1 mx-4 col-span-1">
    <%= render 'layouts/new_room_form'%>
    <h4 class="font-bold">Rooms</h4>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms" class="mb-2 flex flex-col gap-1 w-fit">
      <%= render @rooms %>
    </div>
    <h4 class="font-bold"> Users </h4>
    <%= turbo_stream_from "users" %>
    <div id="users" class="mb-2 flex flex-col gap-1 w-fit">
      <%= render @users %>
    </div>

</div>
  <div class="col-span-2 grid center" id="room_container">
    <% if @single_room %>
      <div id="single_room" class="h-[calc(100vh-175px)]">
        <h4 class="text-center text-3xl font-bold"><%= @user&.email || @single_room.name %></h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages" class="h-[calc(100vh-175px)] overflow-y-scroll overflow-x-hidden chat chat-start w-9/12 my-0 mx-auto">
          <%= render @messages %>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<%= link_to user do %>
<div class="tooltip" data-tip="<%= user.email %>">
  <div class="avatar placeholder flex items-center gap-2">
    <div class="bg-neutral-focus text-neutral-content rounded-full w-10">
      <span><%= user.email.first.capitalize %></span>
    </div>
    <p class="text-center"><%= user.email %></p>
  </div>
</div>
<% end %>